name: Facenet
channels:
  - javascript
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python
  - tensorflow
  - scikit-learn
  - opencv
  - h5py
  - matplotlib
  - Pillow
  - requests
  - psutil
  - xlsxwriter
  - tqdm
